project:
  type: website

website:
  title: "Blog Nest"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rwer0002
format:
  html:
    theme: cosmo
    css: styles.css
